import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {adaptDatabase} from '../server/database.js';
import {handle} from '../server/index.js';
import {verifiedSessionId,publicProfile} from '../server/account.js';
import {cleanSettingsPatch} from '../worker/home.js';
import {parseRSS,handleInfo} from '../worker/info.js';
import {signInPage,authRoute} from '../server/auth.js';
const pg=new PGlite();await pg.exec('CREATE ROLE anon; CREATE ROLE authenticated;');await pg.exec(fs.readFileSync(new URL('../supabase/migrations/202610050001_aura_home.sql',import.meta.url),'utf8'));
await pg.exec('CREATE SCHEMA auth; CREATE TABLE auth.sessions(id uuid PRIMARY KEY,user_id uuid NOT NULL)');
const DB=adaptDatabase(async(s,p)=>{const r=await pg.query(s,p);r.rows.count=r.affectedRows;return r.rows});
const user={id:'bbbbbbbb-bbbb-4bbb-bbbb-bbbbbbbbbbbb',email:'owner@example.test',email_confirmed_at:new Date().toISOString(),user_metadata:{full_name:'Display only',avatar_url:'https://evil.test/image'},app_metadata:{provider:'google'}};
const env={APP_ORIGIN:'https://aura.test',OWNER_EMAIL:user.email,APP_DATA_USER_ID:'legacy-owner',SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_PUBLISHABLE_KEY:'fixture',SUPABASE_SECRET_KEY:'fixture',DATABASE_URL:'fixture'};
const first=crypto.randomUUID(),second=crypto.randomUUID(),third=crypto.randomUUID();let active=first,signouts=0;
await pg.query('INSERT INTO auth.sessions(id,user_id) VALUES($1,$4),($2,$4),($3,$4)',[first,second,third,user.id]);
const session=()=>({client:{auth:{getUser:async()=>({data:{user},error:null}),getSession:async()=>({data:{session:{access_token:'x.'+Buffer.from(JSON.stringify({sub:user.id,session_id:active})).toString('base64url')+'.x'}}}),signOut:async()=>{signouts++;return{error:null}}}},finish:r=>r,clear(){}});
const deps={sessionClient:session,getDatabase:()=>({adapter:DB}),createStorage:()=>({})};
const req=(path,method='GET',body,headers={})=>new Request(env.APP_ORIGIN+path,{method,headers:{...(method==='GET'?{}:{Origin:env.APP_ORIGIN,'Content-Type':'application/json'}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});
assert.equal(publicProfile(user,env).avatar,null);assert.equal(publicProfile(user,env).name,'Display only');
assert.equal(await verifiedSessionId(session(),user),first);
const bad={client:{auth:{getSession:async()=>({data:{session:{access_token:'x.'+Buffer.from(JSON.stringify({sub:'attacker',session_id:first})).toString('base64url')+'.x'}}})}}};await assert.rejects(()=>verifiedSessionId(bad,user));
assert.equal((await handle(req('/api/account'),env,deps)).status,200);active=second;assert.equal((await handle(req('/api/account'),env,deps)).status,200);active=first;
assert.equal((await handle(req('/api/account/devices/revoke','POST',{id:first}),env,deps)).status,400);
assert.equal((await handle(req('/api/account/devices/revoke','POST',{id:second},{Origin:'https://evil.test'}),env,deps)).status,403);
assert.equal((await handle(req('/api/account/devices/revoke','POST',{id:second}),env,deps)).status,200);active=second;
assert.equal((await handle(req('/api/state'),env,deps)).status,401);assert.equal(signouts,1);active=first;
await pg.query('DELETE FROM auth.sessions WHERE id=$1',[third]);active=third;assert.equal((await handle(req('/api/state'),env,deps)).status,401);active=first;
let response=await handle(req('/api/settings','PATCH',{revision:0,patch:{idle:120,hub:{displayName:'Aura Owner',timezones:['Asia/Tokyo'],widgets:['news'],notifications:{news:true},savedNews:[]}}}),env,deps);assert.equal(response.status,200);
response=await handle(req('/api/account/backups','POST',{}),env,deps);assert.equal(response.status,201);const backup=(await response.json()).backup;
response=await handle(req('/api/settings','PATCH',{revision:1,patch:{idle:45}}),env,deps);assert.equal(response.status,200);
assert.equal((await handle(req('/api/account/restore','POST',{backupId:backup.id,revision:1}),env,deps)).status,409);
assert.equal((await handle(req('/api/account/restore','POST',{backupId:backup.id,revision:2}),env,deps)).status,200);
const restored=await DB.prepare('SELECT value,revision FROM home_settings WHERE user_id=?').bind(env.APP_DATA_USER_ID).first();assert.equal(JSON.parse(restored.value).idle,120);assert.equal(restored.revision,3);
await DB.prepare("INSERT INTO home_records(user_id,kind,id,value,revision,updated_at) VALUES(?,'private-test',?,'{\"secret\":\"never-export\"}',1,'now')").bind(env.APP_DATA_USER_ID,crypto.randomUUID()).run();
const exported=await(await handle(req('/api/account/export'),env,deps)).text();assert.ok(exported.includes('Aura Owner'));assert.ok(!exported.includes('never-export'));assert.ok(!exported.includes('devices'));
const recordCount=await DB.prepare("SELECT count(*) AS count FROM home_records WHERE user_id=? AND kind='backups'").bind('other-owner').first();assert.equal(recordCount.count,0);
assert.throws(()=>cleanSettingsPatch({hub:{watchlist:[{id:'1',title:'bad',date:'',type:'movie',url:'http://127.0.0.1/'}]}}));
assert.throws(()=>cleanSettingsPatch({hub:{timezones:['invalid/zone']}}));assert.throws(()=>cleanSettingsPatch({hub:{notifications:{unselected:true}}}));
assert.throws(()=>cleanSettingsPatch({hub:{watchlist:[{id:'1',title:'date',date:'2026-02-30',type:'movie',url:''}]}}));
const largeNews=Array.from({length:40},(_,i)=>({title:'見'.repeat(300),url:'https://example.test/'+String(i)+'/'+ 'a'.repeat(1900),source:'提供元'}));
assert.equal((await handle(req('/api/settings','PATCH',{revision:3,patch:{hub:{savedNews:largeNews}}}),env,deps)).status,200);
assert.equal((await handle(req('/api/settings','PATCH',{revision:4,patch:{hub:{displayName:'a'.repeat(262145)}}}),env,deps)).status,413);
const feed='<rss><channel><item><title>Test &amp; News</title><link>https://example.test/story</link><pubDate>Mon, 05 Oct 2026 12:00:00 GMT</pubDate></item><item><title>Bad</title><link>javascript:alert(1)</link></item></channel></rss>';
assert.equal(parseRSS(feed).length,1);assert.equal(parseRSS(feed)[0].title,'Test & News');assert.throws(()=>parseRSS('<!DOCTYPE x [<!ENTITY a "abc">]><rss/>'));
assert.equal((await handleInfo(req('/api/info/news?source=http://127.0.0.1'),env,new URL(env.APP_ORIGIN+'/api/info/news?source=http://127.0.0.1'))).status,400);
assert.equal((await handleInfo(req('/api/info/transit?operator=invalid'),env,new URL(env.APP_ORIGIN+'/api/info/transit?operator=invalid'))).status,400);
const expiredCallback=await handle(req('/?error=invalid_request&error_code=bad_oauth_state'),{...env,GOOGLE_AUTH_ENABLED:'true'},deps);assert.equal(expiredCallback.status,400);const expiredHTML=await expiredCallback.text();assert.ok(expiredHTML.includes('サインインが完了しませんでした'));assert.ok(expiredHTML.includes('Googleで続ける'));assert.ok(!expiredHTML.includes('aura-app'));
const googleHTML=await signInPage('',200,{google:true}).text();assert.ok(googleHTML.indexOf('Googleで続ける')<googleHTML.indexOf('メールアドレス'));assert.ok(googleHTML.includes('メールで続ける'));
const oauthRequest=new Request(env.APP_ORIGIN+'/auth/google',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:''});
const oauthSession={client:{auth:{signInWithOAuth:async()=>({data:{url:env.SUPABASE_URL+'/auth/v1/authorize?provider=google'},error:null})}}};
const oauthResponse=await authRoute(oauthRequest,{...env,GOOGLE_AUTH_ENABLED:'true'},oauthSession);assert.equal(oauthResponse.status,200);assert.ok(oauthResponse.headers.get('Content-Security-Policy').includes("form-action 'self'"));assert.ok((await oauthResponse.text()).includes('location.replace('));
const wrongDestination={client:{auth:{signInWithOAuth:async()=>({data:{url:'https://evil.test/authorize'},error:null})}}};assert.equal((await authRoute(oauthRequest,{...env,GOOGLE_AUTH_ENABLED:'true'},wrongDestination)).status,502);
console.log('PASS: verified session ownership/presence, immediate remote revocation, CSRF, profile safety, backup restore/conflict, secret-free export, strict app settings, RSS entity/URL protections, Google-first login.');
await pg.close();
