import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {adaptDatabase} from '../server/database.js';
import {handleGoogle,googleSources,seal,unseal,normalizeGoogleEvent} from '../worker/google.js';
import {handleHome} from '../worker/home.js';
const pg=new PGlite();await pg.exec('CREATE ROLE anon; CREATE ROLE authenticated;');await pg.exec(fs.readFileSync(new URL('../supabase/migrations/202610050001_aura_home.sql',import.meta.url),'utf8'));
const DB=adaptDatabase(async(sql,args)=>{const r=await pg.query(sql,args);r.rows.count=r.affectedRows;return r.rows});
const objects=new Map();const BUCKET={async get(key){const value=objects.get(key);return value?{json:async()=>JSON.parse(value),text:async()=>value}:null},async put(key,value){objects.set(key,value)},async delete(key){for(const k of Array.isArray(key)?key:[key])objects.delete(k)},async list({prefix}){return{objects:[...objects.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}}};
const origin='https://aura-home-hakky.haka01xx627846.chatgpt.site';const scopes='openid email https://www.googleapis.com/auth/calendar.calendarlist.readonly https://www.googleapis.com/auth/calendar.events.readonly';
const env={DB,BUCKET,GOOGLE_CLIENT_ID:'fixture-client',GOOGLE_CLIENT_SECRET:'fixture-secret',GOOGLE_REDIRECT_URI:origin+'/api/google/callback',GOOGLE_TOKEN_KEY:Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('base64')};
let refreshes=0,eventReads=0,deniedRefresh=false,eventFailure=0,currentSubject='google-a',pauseToken=null;
let eventItems=[{id:'all-day',summary:'終日',start:{date:'2026-10-05'},end:{date:'2026-10-07'}},{id:'changed-instance',recurringEventId:'weekly',originalStartTime:{dateTime:'2026-10-05T09:00:00+09:00'},summary:'変更された回',start:{dateTime:'2026-10-05T10:00:00+09:00',timeZone:'Asia/Tokyo'},end:{dateTime:'2026-10-05T11:00:00+09:00'}},{id:'cancelled',status:'cancelled',start:{date:'2026-10-05'},end:{date:'2026-10-06'}},{id:'dst',start:{dateTime:'2026-11-01T01:30:00-04:00',timeZone:'America/New_York'},end:{dateTime:'2026-11-01T01:30:00-05:00'}}];
globalThis.fetch=async(input,options={})=>{const url=new URL(input);if(url.hostname==='oauth2.googleapis.com'&&url.pathname==='/token'){const params=new URLSearchParams(options.body);if(pauseToken)await pauseToken;if(params.get('grant_type')==='refresh_token'){refreshes++;if(deniedRefresh)return Response.json({error:'invalid_grant'},{status:400})}return Response.json({access_token:'fixture-access-'+refreshes,refresh_token:'fixture-refresh',expires_in:3600,scope:scopes})}if(url.pathname==='/revoke')return new Response(null,{status:200});if(url.hostname==='openidconnect.googleapis.com')return Response.json({sub:currentSubject,email:currentSubject+'@example.test',email_verified:true});if(url.pathname.endsWith('/calendarList')){return Response.json(url.searchParams.has('pageToken')?{items:[{id:'other',summary:'別カレンダー',timeZone:'America/New_York',accessRole:'reader'}]}:{items:[{id:'primary',summary:'仕事',primary:true,timeZone:'Asia/Tokyo',accessRole:'owner'}],nextPageToken:'page-2'})}if(url.pathname.endsWith('/events')){eventReads++;assert.equal(url.searchParams.get('singleEvents'),'true');assert.equal(url.searchParams.get('showDeleted'),'false');assert.ok(url.searchParams.get('timeMin').endsWith('Z'));if(eventFailure)return Response.json({error:{errors:[{reason:eventFailure===429?'rateLimitExceeded':'backendError'}]}},{status:eventFailure,headers:{'Retry-After':'30'}});if(!url.searchParams.has('pageToken'))return Response.json({items:eventItems.slice(0,2),nextPageToken:'next'});return Response.json({items:eventItems.slice(2)})}if(url.hostname==='calendar.google.com')return new Response('BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:ical-fixture\r\nDTSTART;VALUE=DATE:20261005\r\nDTEND;VALUE=DATE:20261006\r\nSUMMARY:iCal予定\r\nEND:VEVENT\r\nEND:VCALENDAR');throw Error('Unexpected provider route '+url.pathname)};
function req(path,method='GET',value,user='a',headers={}){return new Request(origin+path,{method,headers:{'oai-authenticated-user-id':user,...(method==='GET'?{}:{Origin:origin,'Content-Type':'application/json'}),...headers},...(value===undefined?{}:{body:JSON.stringify(value)})})}
async function call(path,method='GET',value,user='a',headers={}){const request=req(path,method,value,user,headers);return handleGoogle(request,env,new URL(request.url))}
async function start(user='a'){const response=await call('/api/google/connect','POST',undefined,user);assert.equal(response.status,303);const auth=new URL(response.headers.get('Location'));assert.equal(auth.searchParams.get('code_challenge_method'),'S256');assert.equal(auth.searchParams.get('redirect_uri'),env.GOOGLE_REDIRECT_URI);assert.ok(response.headers.get('Set-Cookie').includes('HttpOnly'));return{state:auth.searchParams.get('state'),cookie:response.headers.get('Set-Cookie').split(';')[0]}}
const cb=(flow,user='a',extra='')=>call('/api/google/callback?state='+flow.state+'&code=fixture-code'+extra,'GET',undefined,user,{Cookie:flow.cookie});
assert.equal((await handleGoogle(new Request(origin+'/api/google/status'),env,new URL(origin+'/api/google/status'))).status,401);
assert.equal((await call('/api/google/connect','POST',undefined,'a',{Origin:'https://evil.test'})).status,403);
assert.equal((await handleGoogle(req('/api/google/status'),{DB,BUCKET},new URL(origin+'/api/google/status'))).status,200);
assert.equal((await handleGoogle(req('/api/google/connect','POST'),{DB,BUCKET},new URL(origin+'/api/google/connect'))).status,503);
const first=await start();assert.ok((await cb(first,'b')).headers.get('Location').includes('invalid_state'));assert.ok((await call('/api/google/callback?state='+first.state+'&code=x')).headers.get('Location').includes('invalid_state'));assert.ok((await cb(first)).headers.get('Location').includes('connected'));assert.ok((await cb(first)).headers.get('Location').includes('invalid_state'));
let row=(await DB.prepare('SELECT * FROM google_accounts WHERE user_id=?').bind('a').first());assert.ok(!row.tokens.includes('fixture'));assert.equal((await unseal(env,'a',row.tokens)).refreshToken,'fixture-refresh');await assert.rejects(()=>unseal(env,'b',row.tokens));
assert.equal((await (await call('/api/google/status','GET',undefined,'b')).json()).connected,false);
let status=await (await call('/api/google/calendars')).json();assert.equal(status.calendars.length,2);assert.deepEqual(status.selected,['primary']);assert.ok(!JSON.stringify(status).includes('fixture-access'));
assert.equal((await call('/api/google/selection','PUT',{selected:['primary'],revision:status.revision-1,connectionId:status.connectionId})).status,409);
assert.equal((await call('/api/google/selection','PUT',{selected:['arbitrary'],revision:status.revision,connectionId:status.connectionId})).status,400);
assert.equal((await call('/api/google/selection','PUT',{selected:[],revision:status.revision,connectionId:'old'})).status,409);
const from='2026-10-01T00:00:00.000Z',to='2026-11-10T00:00:00.000Z';let sources=await googleSources(env,'a',from,to,true);assert.equal(sources[0].events.length,3);assert.equal(sources[0].events.find(e=>e.title==='終日').end,'2026-10-07');assert.equal(sources[0].events.find(e=>e.recurringEventId).start,'2026-10-05T01:00:00.000Z');assert.equal(sources[0].events.find(e=>e.id.endsWith(':dst')).end,'2026-11-01T06:30:00.000Z');
const reads=eventReads;await googleSources(env,'a',from,to,false);assert.equal(eventReads,reads);
eventItems=eventItems.filter(e=>e.id!=='changed-instance');sources=await googleSources(env,'a',from,to,true);assert.equal(sources[0].events.length,2);
eventFailure=503;sources=await googleSources(env,'a',from,to,true);assert.ok(sources[0].stale);assert.equal(sources[0].events.length,2);assert.ok(sources[0].updatedAt);
eventFailure=429;sources=await googleSources(env,'a',from,to,true);assert.equal(sources[0].code,'rate_limited');const limitedReads=eventReads;await googleSources(env,'a',from,to,true);assert.equal(eventReads,limitedReads);eventFailure=0;objects.clear();
row=(await DB.prepare('SELECT * FROM google_accounts WHERE user_id=?').bind('a').first());const expired=await unseal(env,'a',row.tokens);expired.expiresAt=0;await DB.prepare('UPDATE google_accounts SET tokens=? WHERE user_id=?').bind(await seal(env,'a',expired),'a').run();await call('/api/google/calendars');assert.equal(refreshes,1);
row=(await DB.prepare('SELECT * FROM google_accounts WHERE user_id=?').bind('a').first());expired.expiresAt=0;await DB.prepare('UPDATE google_accounts SET tokens=? WHERE user_id=?').bind(await seal(env,'a',expired),'a').run();deniedRefresh=true;assert.equal((await (await call('/api/google/calendars')).json()).code,'reauthentication_required');deniedRefresh=false;
const reconnect=await start();assert.ok((await cb(reconnect)).headers.get('Location').includes('connected'));status=await (await call('/api/google/calendars')).json();
// Existing iCal and local events still coexist with Google API data.
await DB.prepare('INSERT INTO home_records VALUES(?,?,?,?,?,?)').bind('a','events','11111111-1111-1111-1111-111111111111',JSON.stringify({title:'アプリ内予定',start:'2026-10-05',end:'2026-10-06',allDay:true}),1,new Date().toISOString()).run();
await DB.prepare('INSERT INTO calendar_sources VALUES(?,?,?,?,?)').bind('a','22222222-2222-2222-2222-222222222222','iCal','https://calendar.google.com/calendar/ical/test/public/basic.ics',new Date().toISOString()).run();
let homeRequest=req('/api/calendar?from='+from+'&to='+to+'&refresh=1'),home=await (await handleHome(homeRequest,env,new URL(homeRequest.url))).json();assert.equal(home.sources.length,2);assert.equal(home.sources[0].events[0].title,'iCal予定');
const stateRequest=req('/api/state'),state=await (await handleHome(stateRequest,env,new URL(stateRequest.url))).json();assert.equal(state.events[0].title,'アプリ内予定');
assert.equal((await call('/api/google/disconnect','POST',{revision:status.revision-1,connectionId:status.connectionId})).status,409);assert.equal((await call('/api/google/disconnect','POST',{revision:status.revision,connectionId:status.connectionId})).status,200);assert.deepEqual(await googleSources(env,'a',from,to,true),[]);assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM home_records').bind().first()).n,1);assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM calendar_sources').bind().first()).n,1);
const expiredFlow=await start();await DB.prepare('UPDATE google_oauth_states SET expires_at=0 WHERE user_id=?').bind('a').run();assert.ok((await cb(expiredFlow)).headers.get('Location').includes('invalid_state'));
const cancelled=await start();assert.ok((await cb(cancelled,'a','&error=access_denied')).headers.get('Location').includes('denied'));
// A disconnect during the callback cannot re-create a connection.
const pending=await start();let release;pauseToken=new Promise(resolve=>release=resolve);const inFlight=cb(pending);await new Promise(resolve=>setTimeout(resolve,30));await call('/api/google/disconnect','POST',{});release();pauseToken=null;assert.ok((await inFlight).headers.get('Location').includes('invalid_state'));assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM google_accounts').bind().first()).n,0);
const otherFlow=await start('b');currentSubject='google-b';assert.ok((await cb(otherFlow,'b')).headers.get('Location').includes('connected'));assert.equal((await (await call('/api/google/status')).json()).connected,false);
assert.equal(normalizeGoogleEvent({status:'cancelled'},{id:'x'}),null);
console.log('PASS: Postgres migrations, auth/CSRF/PKCE/state replay/expiry, encrypted user isolation, revision conflicts, pagination, recurrence exceptions/cancellation, all-day/DST, refresh/re-auth, stale recovery/rate-limit, iCal/local preservation, disconnect races.');

await pg.close();
