import assert from 'node:assert/strict';
import fs from 'node:fs';
import {PGlite} from '@electric-sql/pglite';
import {adaptDatabase,postgresQuery} from '../server/database.js';
import {handle,sanitizedRequest,normalizeRequest} from '../server/index.js';
import {sessionClient,isOwner} from '../server/auth.js';
import {handleHome} from '../worker/home.js';
const pg=new PGlite();await pg.exec('CREATE ROLE anon; CREATE ROLE authenticated;');await pg.exec(fs.readFileSync(new URL('../supabase/migrations/202610050001_aura_home.sql',import.meta.url),'utf8'));
const DB=adaptDatabase(async(sql,params)=>{const result=await pg.query(sql,params);result.rows.count=result.affectedRows;return result.rows});
assert.equal(postgresQuery("SELECT '?' AS question WHERE id=? AND name='it''s?'"),"SELECT '?' AS question WHERE id=$1 AND name='it''s?'");
const objects=new Map(),BUCKET={get:async key=>objects.has(key)?{json:async()=>JSON.parse(objects.get(key)),text:async()=>objects.get(key),customMetadata:{}}:null,put:async(k,v)=>objects.set(k,v),delete:async k=>objects.delete(k),list:async()=>({objects:[]})};
const env={APP_ORIGIN:'https://aura.test',OWNER_EMAIL:'owner@example.test',APP_DATA_USER_ID:'legacy-owner',SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_PUBLISHABLE_KEY:'public-fixture',SUPABASE_SECRET_KEY:'secret-fixture',DATABASE_URL:'fixture'},user={id:'new-auth-id',email:env.OWNER_EMAIL,email_confirmed_at:new Date().toISOString()};
const request=(path,method='GET',body,headers={})=>new Request(env.APP_ORIGIN+path,{method,headers:{...(method==='GET'?{}:{Origin:env.APP_ORIGIN,'Content-Type':'application/json'}),...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});
let calls=0,logout=0;
const dependencies={getSessionId:async()=>"aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa",sessionClient:()=>({client:{auth:{getUser:async()=>({data:{user},error:null}),signOut:async()=>{logout++}}},finish:r=>r}),getDatabase:()=>{calls++;return{adapter:DB}},createStorage:()=>BUCKET,worker:{fetch:(r,e)=>handleHome(r,e,new URL(r.url))}};
let response=await handle(request('/api/state','GET',undefined,{'oai-authenticated-user-id':'attacker','oai-authenticated-user-email':'attacker@example.test'}),env,dependencies);assert.equal(response.status,200);assert.equal((await response.json()).account.email,user.email);
assert.equal(sanitizedRequest(request('/api/state','GET',undefined,{'oai-other':'fake'}),user,env).headers.get('oai-other'),null);
assert.equal(sanitizedRequest(request('/api/state'),user,env).headers.get('oai-authenticated-user-id'),'legacy-owner');
response=await handle(request('/api/settings','PATCH',{revision:0,patch:{idle:120}}),env,dependencies);assert.equal(response.status,200);assert.equal((await response.json()).revision,1);
assert.equal((await handle(request('/api/settings','PATCH',{revision:0,patch:{idle:45}}),env,dependencies)).status,409);
const task={id:crypto.randomUUID(),title:'Postgres test',done:false,due:null};
response=await handle(request('/api/tasks','POST',task),env,dependencies);assert.equal(response.status,201);const record=(await response.json()).record;
assert.equal((await handle(request('/api/tasks','POST',task),env,dependencies)).status,201);assert.equal((await DB.prepare("SELECT COUNT(*) AS count FROM home_records WHERE kind='tasks'").bind().first()).count,1);
assert.equal((await handle(request('/api/tasks/'+task.id,'PUT',{...record,title:'Changed',revision:1}),env,dependencies)).status,200);
assert.equal((await handle(request('/api/tasks/'+task.id,'DELETE',{revision:1}),env,dependencies)).status,409);
assert.equal((await handle(request('/api/tasks/'+task.id,'DELETE',{revision:2}),env,dependencies)).status,200);
assert.equal((await DB.prepare('SELECT user_id FROM home_settings').bind().first()).user_id,env.APP_DATA_USER_ID);
const denied={...dependencies,sessionClient:()=>({client:{auth:{getUser:async()=>({data:{user:{...user,email:'other@example.test'}},error:null}),signOut:async()=>{logout++}}},finish:r=>r})};
const before=calls;assert.equal((await handle(request('/api/state'),env,denied)).status,403);assert.equal(calls,before);assert.equal(logout,1);
let sent=0,cleared=0;
const forms={...dependencies,sessionClient:()=>({client:{auth:{signInWithOtp:async value=>{sent++;assert.equal(value.options.emailRedirectTo,env.APP_ORIGIN+'/auth/callback');return{error:null}},verifyOtp:async value=>({data:{user},error:value.token==='123456'||value.token_hash==='abcdef1234567890abcdef'?null:{status:400}}),signOut:async()=>{throw Error('Network unavailable')}}},clear:()=>{cleared++},finish:r=>r})};
const formRequest=(path,form)=>new Request(env.APP_ORIGIN+path,{method:'POST',headers:{Origin:env.APP_ORIGIN,'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(form)});
assert.equal((await handle(formRequest('/auth/email',{email:'other@example.test'}),env,forms)).status,403);assert.equal(sent,0);
assert.equal((await handle(formRequest('/auth/email',{email:env.OWNER_EMAIL}),env,forms)).status,200);assert.equal(sent,1);
assert.equal((await handle(formRequest('/auth/email',{email:'x'.repeat(5000)}),env,forms)).status,413);
assert.equal((await handle(formRequest('/auth/verify',{email:env.OWNER_EMAIL,token:'123456'}),env,forms)).headers.get('Location'),'/');
assert.equal((await handle(request('/auth/confirm?token_hash=abcdef1234567890abcdef'),env,forms)).status,200);
assert.equal((await handle(formRequest('/auth/confirm',{token_hash:'abcdef1234567890abcdef'}),env,forms)).headers.get('Location'),'/');
assert.equal((await handle(formRequest('/auth/logout',{}),env,forms)).status,200);assert.equal(cleared,1);
const anonymous={...dependencies,sessionClient:()=>({client:{auth:{getUser:async()=>({data:{user:null},error:{status:401}})}},finish:r=>r})};
assert.equal((await handle(request('/api/state'),env,anonymous)).status,401);assert.equal((await handle(request('/'),env,anonymous)).headers.get('Location'),'/signin');assert.equal(calls,before);
assert.equal((await handle(request('/api/tasks','POST',task,{Origin:'https://evil.test'}),env,dependencies)).status,403);
assert.equal((await handle(request('/'),{},dependencies)).status,503);
assert.equal(isOwner({...user,email_confirmed_at:null},env),false);
assert.equal(normalizeRequest(new Request('https://deployment.test/api/entry?__aura_path=/api/state&month=10'),env).url,'https://aura.test/api/state?month=10');
// SSR package itself: server cookies remain HttpOnly, Secure, SameSite=Lax.
const fetchBefore=globalThis.fetch;
globalThis.fetch=async()=>Response.json({access_token:'fake-access',refresh_token:'fake-refresh',expires_in:3600,expires_at:Math.floor(Date.now()/1000)+3600,token_type:'bearer',user});
const session=sessionClient(request('/auth/verify'),env);const verified=await session.client.auth.verifyOtp({email:user.email,token:'123456',type:'email'});assert.equal(verified.error,null);
const cookies=session.finish(new Response('OK')).headers.getSetCookie().join(';');assert.ok(cookies.includes('HttpOnly'));assert.ok(cookies.includes('Secure'));assert.ok(cookies.includes('SameSite=Lax'));assert.ok(!cookies.includes('Domain='));session.clear();assert.ok(session.finish(new Response('OK')).headers.getSetCookie().every(c=>c.includes('Max-Age=0')));globalThis.fetch=fetchBefore;
// Browser SQL roles cannot see private application data even with a direct API token.
await pg.exec('SET ROLE authenticated;');await assert.rejects(()=>pg.query('SELECT * FROM home_settings'));await pg.exec('RESET ROLE;');
await pg.close();console.log('PASS: Postgres schema/adapter, settings and record revision conflicts, idempotent writes, legacy identity mapping, owner-only and unconfirmed/anonymous rejection, header spoof protection, CSRF, SSR cookie flags, RLS/table permissions, missing setup fails closed.');

