const pages={
 '/about':{title:'Aura Homeについて',body:'<p>時計、天気、音楽、予定、ToDo、ニュースをまとめたホームアプリです。Googleアカウントでログインして、自分の設定を保存できます。</p><p>ソースコードはMITライセンスで公開します。自分の環境に設置したり、改善に参加したりできます。</p><p><a href="https://github.com/tstyr/aura-home">ソースコード・開発への参加</a></p>'},
 '/privacy':{title:'プライバシーポリシー',body:'<p>更新日：2026年10月5日</p><h2>保存する情報</h2><p>ログインにはGoogleから提供されるメールアドレス、名前、プロフィール画像を使います。設定、ToDo、予定、タイマー、背景画像、端末セッション、バックアップはアカウントごとに保存します。</p><h2>Googleカレンダー</h2><p>連携は任意で、一覧と予定の読み取りだけを行います。接続トークンはサーバーで暗号化して保存し、カレンダーの表示に使います。書き込みや第三者への販売、広告、AIモデルの学習には使用しません。</p><h2>利用する外部サービス</h2><p>認証・データ保存にSupabase、ホスティングにVercelを使います。天気、音楽、ニュース、スポーツ、作品情報の取得時は、それぞれの提供元に選択した地域や公開プロフィールなどの取得条件を送ります。リンク先では提供元の規約が適用されます。</p><h2>端末内の保存</h2><p>表示設定とオフライン用タイマーを利用者別にこのブラウザへ保存します。現在地を利用する場合は端末の許可を求め、現在地の座標を同期設定へ保存しません。</p><h2>データの管理と削除</h2><p>アカウント設定からデータを書き出し、Google連携を解除できます。アカウントを削除すると、このサービスの設定・予定・画像・バックアップ・ログイン情報を削除します。Google側の許可も必要に応じてGoogleアカウントの設定で取り消せます。サービス提供者のバックアップや運用ログには、その提供者の保存期間が適用されます。</p><h2>問い合わせ</h2><p><a href="https://github.com/tstyr/aura-home/issues">不具合・改善の窓口</a>にパスワード、認証コード、秘密鍵や個人の予定を投稿しないでください。自分で設置した環境では、その環境の運営者がデータを管理します。</p>'},
 '/terms':{title:'利用について',body:'<p>Aura Homeは開発中のサービスです。Googleアカウントで初回利用とログインを行い、利用者ごとに独立したデータを管理します。</p><p>外部サービスのデータは取得上限、更新間隔、審査、通信状況の影響を受けます。天気や運行情報などは提供元の最新情報も確認してください。</p><p>他人のデータへのアクセス、認証の回避、不正な大量アクセスを禁止します。大切なデータは書き出し機能で手元にも保存してください。</p><p>アプリを閉じている間のPush通知、映画の自動取得、交通のライブ情報などは、利用できる設定と機能に制限があります。</p><p>ソースコードの利用条件はMITライセンスです。Googleや各情報提供元のデータ、利用者がアップロードした画像には、それぞれの権利・規約が適用されます。</p>'}
};
export function publicPage(path){
 const page=pages[path];if(!page)return null;
 return new Response(`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title} — Aura Home</title><style>body{font:16px system-ui;line-height:1.8;background:#383838;color:#eee;margin:auto;padding:32px 24px;max-width:760px}h1{font-size:28px}h2{font-size:20px;margin-top:28px}a{color:#c8d8ff}nav{display:flex;gap:18px;flex-wrap:wrap}footer{margin-top:40px}</style><nav><a href="/">Aura Home</a><a href="/about">紹介</a><a href="/privacy">プライバシー</a><a href="/terms">利用について</a></nav><main><h1>${page.title}</h1>${page.body}</main><footer>Aura Home · Open source</footer></html>`,{headers:{'Content-Type':'text/html;charset=utf-8','Cache-Control':'public,max-age=300','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'",'X-Content-Type-Options':'nosniff'}});
}
