import ICAL from 'ical.js';
import {cleanDesign} from './design-settings.js';
import {googleConfigured,googleSources} from './google.js';
import {HUB_APPS,cleanHub} from './hub-settings.js';

const reply=(value,status=200)=>Response.json(value,{status,headers:{'Cache-Control':'private, no-store'}});
const UUID=/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/;
const apps=['clock','weather','timer','stats','background','settings','calendar','tasks',...HUB_APPS];
const error=(message,status=400)=>Object.assign(new Error(message),{status});
const number=(n,min,max)=>{if(typeof n!=='number'||!Number.isFinite(n)||n<min||n>max)throw error('数値を確認してください。');return n};
const text=(v,max,required=false)=>{if(typeof v!=='string'||v.length>max||(required&&!v.trim()))throw error('入力内容を確認してください。');return v.trim()};
function checkWrite(request,url){if((request.headers.get('origin')&&request.headers.get('origin')!==url.origin)||request.headers.get('sec-fetch-site')==='cross-site')throw error('この操作はアプリ内から実行してください。',403)}
async function bodyJSON(request,max=262144){if(request.headers.get('content-type')?.split(';')[0]!=='application/json')throw error('入力内容を読み込めません。',415);const data=await limitedText(request.body,max);try{return JSON.parse(data)}catch{throw error('入力内容を読み込めません。')}}
async function limitedText(stream,max){if(!stream)throw error('入力内容がありません。');const reader=stream.getReader(),chunks=[];let total=0;while(true){const{done,value}=await reader.read();if(done)break;total+=value.byteLength;if(total>max){await reader.cancel();throw error('データが大きすぎます。',413)}chunks.push(value)}const bytes=new Uint8Array(total);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.byteLength}return new TextDecoder().decode(bytes)}
export function cleanSettingsPatch(value){if(!value||Array.isArray(value)||typeof value!=='object')throw error('設定内容を確認してください。');const out={};for(const[k,v]of Object.entries(value)){switch(k){
 case'idle':if(![0,15,45,120,300].includes(v))throw error('待機時間を確認してください。');out[k]=v;break;
 case'clock24':case'keepAwake':case'clockSeconds':case'homeAgenda':if(typeof v!=='boolean')throw error('設定内容を確認してください。');out[k]=v;break;
 case'clockSize':out[k]=number(v,.7,1.4);break;
 case'clockWeight':if(![600,700,800,900].includes(v))throw error('文字の太さを確認してください。');out[k]=v;break;
 case'tileOrder':if(!Array.isArray(v)||v.length<8||v.length>apps.length||new Set(v).size!==v.length||v.some(a=>!apps.includes(a))||apps.slice(0,8).some(a=>!v.includes(a)))throw error('アプリの並び順を確認してください。');out[k]=v;break;
 case'hub':out[k]=cleanHub(v);break;
 case'design':out[k]=cleanDesign(v);break;
 case'location':if(v===null){out[k]=null;break}out[k]={name:text(v.name,60,true),lat:number(v.lat,-90,90),lon:number(v.lon,-180,180)};break;
 case'background':if(!v||!['preset','image'].includes(v.kind))throw error('背景を確認してください。');if(v.kind==='preset'&&!['gray','graphite','silver','charcoal'].includes(v.id))throw error('背景を確認してください。');if(v.kind==='image'&&!UUID.test(v.id))throw error('背景画像を確認してください。');out[k]={kind:v.kind,id:v.id,name:typeof v.name==='string'?v.name.slice(0,120):'',dim:number(v.dim??.3,0,.8),blur:number(v.blur??0,0,24),x:number(v.x??50,0,100),y:number(v.y??50,0,100),rotation:number(v.rotation??0,0,1440),slides:Array.isArray(v.slides)?v.slides.filter(id=>typeof id==='string'&&UUID.test(id)).slice(0,100):[]};break;
 default:throw error('未対応の設定です。');
 }}return out}
async function settingsRow(db,user){const row=await db.prepare('SELECT value,revision,updated_at FROM home_settings WHERE user_id=?').bind(user).first();return row?{settings:JSON.parse(row.value),revision:row.revision,updatedAt:row.updated_at}:{settings:{},revision:0,updatedAt:null}}
const recordRow=row=>({...JSON.parse(row.value),id:row.id,revision:row.revision,updatedAt:row.updated_at});
async function records(db,user,kind){const result=await db.prepare('SELECT id,value,revision,updated_at FROM home_records WHERE user_id=? AND kind=? ORDER BY updated_at DESC LIMIT 500').bind(user,kind).all();return result.results.map(recordRow)}
async function sources(db,user){const result=await db.prepare('SELECT id,name,updated_at FROM calendar_sources WHERE user_id=? ORDER BY updated_at LIMIT 10').bind(user).all();return result.results.map(r=>({id:r.id,name:r.name,updatedAt:r.updated_at,provider:'google-ical'}))}
function cleanRecord(kind,v){if(kind==='tasks'){return{title:text(v.title,200,true),due:v.due?validDay(v.due):null,done:Boolean(v.done)}}if(kind==='events'){const allDay=Boolean(v.allDay),start=allDay?validDay(v.start):validISO(v.start),end=allDay?validDay(v.end):validISO(v.end);if(end<=start)throw error('終了を開始より後にしてください。');return{title:text(v.title,200,true),start,end,allDay,location:typeof v.location==='string'?v.location.slice(0,200):''}}
 if(kind==='timers'){const mode=v.mode==='pomodoro'?'pomodoro':'timer';return{title:text(v.title,80,true),mode,duration:number(v.duration,1,86400),remaining:number(v.remaining,0,86400),end:v.end===null?null:number(v.end,0,Date.now()+86400000),done:Boolean(v.done),phase:v.phase==='break'?'break':'focus',cycle:number(v.cycle??1,1,20),cycles:number(v.cycles??4,1,20),focusSeconds:number(v.focusSeconds??1500,60,86400),breakSeconds:number(v.breakSeconds??300,60,3600)}}throw error('見つかりません。',404)}
function validDay(v){if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v+'T00:00:00Z').toISOString().slice(0,10)!==v)throw error('日付を確認してください。');return v}
function validISO(v){if(typeof v!=='string'||!Number.isFinite(Date.parse(v))||v.length>40)throw error('日時を確認してください。');return new Date(v).toISOString()}
export function googleCalendarURL(value){let u;try{u=new URL(value)}catch{throw error('GoogleカレンダーのiCal URLを入力してください。')}if(u.protocol!=='https:'||!['calendar.google.com','www.google.com'].includes(u.hostname)||u.username||u.password||u.port||u.hash||u.search||!/^\/calendar\/ical\/[^/]+\/(?:private-[a-zA-Z0-9]+|public)\/basic\.ics$/.test(u.pathname))throw error('GoogleカレンダーのiCal URLを入力してください。');return u.href}
function calendarTime(time){return time.isDate?time.toString().slice(0,10):time.toJSDate().toISOString()}
export function parseCalendarICS(raw,from,to,source){const root=new ICAL.Component(ICAL.parse(raw));if(root.name!=='vcalendar')throw error('カレンダーの形式を読み込めませんでした。',422);const components=root.getAllSubcomponents('vevent');if(components.length>5000)throw error('予定が多すぎます。対象のカレンダーを分けてください。',413);const items=[],warnings=[];let expansions=0;for(const component of components){const event=new ICAL.Event(component);if(event.isRecurrenceException())continue;const add=details=>{const entry=details.item;if(entry.component.getFirstPropertyValue('status')==='CANCELLED')return;const start=calendarTime(details.startDate),end=calendarTime(details.endDate),allDay=details.startDate.isDate;if(Date.parse(end)<=Date.parse(from)||Date.parse(start)>=Date.parse(to))return;items.push({id:source.id+':'+event.uid+':'+start,title:String(entry.summary||'予定').slice(0,200),start,end,allDay,location:String(entry.location||'').slice(0,200),sourceId:source.id,sourceName:source.name,readOnly:true})};if(!event.isRecurring()){add({item:event,startDate:event.startDate,endDate:event.endDate});continue}const iterator=event.iterator();let occurrence;while((occurrence=iterator.next())){if(++expansions>20000){warnings.push('繰り返し予定の一部を省略しました。');break}const details=event.getOccurrenceDetails(occurrence);if(calendarTime(details.startDate)>=to)break;add(details);if(items.length>=500){warnings.push('表示は500件までです。');break}}if(expansions>20000||items.length>=500)break}return{events:items,warnings:[...new Set(warnings)]}}
async function calendarFeed(source,env,user,force){const key='calendar-cache/'+encodeURIComponent(user)+'/'+source.id+'.ics',cached=await env.BUCKET.get(key),last=cached?.customMetadata?.fetchedAt;let raw,updatedAt=last||null,stale=false,problem=null;if(cached&&!force&&Date.now()-Date.parse(last)<600000)raw=await cached.text();else{const abort=new AbortController(),timeout=setTimeout(()=>abort.abort(),12000);try{const response=await fetch(googleCalendarURL(source.url),{headers:{Accept:'text/calendar'},redirect:'error',signal:abort.signal});if(!response.ok)throw error(response.status===404?'URLが無効か、カレンダーを取得できません。':'Googleカレンダーを取得できません。',502);raw=await limitedText(response.body,2*1024*1024);if(!raw.includes('BEGIN:VCALENDAR'))throw error('iCal形式のデータではありません。',422);new ICAL.Component(ICAL.parse(raw));updatedAt=new Date().toISOString();await env.BUCKET.put(key,raw,{httpMetadata:{contentType:'text/calendar'},customMetadata:{fetchedAt:updatedAt}})}catch(e){if(!cached)throw error(e.name==='AbortError'?'カレンダーの取得に時間がかかっています。':e.message||'カレンダーを取得できません。',502);raw=await cached.text();stale=true;problem='更新できなかったため、前回の予定を表示しています。'}finally{clearTimeout(timeout)}}return{raw,updatedAt,stale,error:problem}}

export async function handleHome(request,env,url){const user=request.headers.get('oai-authenticated-user-id');if(!user)return reply({error:'サインインしてください。'},401);if(!env.DB||!env.BUCKET)return reply({error:'保存先に接続できません。'},503);try{
 if(request.method!=='GET')checkWrite(request,url);
 if(url.pathname==='/api/state'&&request.method==='GET'){const[settings,tasks,timers,events,calendars]=await Promise.all([settingsRow(env.DB,user),records(env.DB,user,'tasks'),records(env.DB,user,'timers'),records(env.DB,user,'events'),sources(env.DB,user)]);return reply({...settings,tasks,timers,events,calendars,account:env.AUTH_PROFILE||{email:request.headers.get('oai-authenticated-user-email')||null},googleOAuthAvailable:googleConfigured(env)})}
 if(url.pathname==='/api/settings'&&request.method==='PATCH'){const body=await bodyJSON(request),patch=cleanSettingsPatch(body.patch);number(body.revision,0,1e9);const current=await settingsRow(env.DB,user);if(current.revision!==body.revision)return reply({error:'別の端末で設定が更新されました。',...current},409);const value=JSON.stringify({...current.settings,...patch}),at=new Date().toISOString();const row=await env.DB.prepare('INSERT INTO home_settings(user_id,value,revision,updated_at) VALUES(?,?,1,?) ON CONFLICT(user_id) DO UPDATE SET value=excluded.value,revision=home_settings.revision+1,updated_at=excluded.updated_at WHERE home_settings.revision=? RETURNING value,revision,updated_at').bind(user,value,at,body.revision).first();if(!row)return reply({error:'別の端末で設定が更新されました。',...await settingsRow(env.DB,user)},409);return reply({settings:JSON.parse(row.value),revision:row.revision,updatedAt:row.updated_at})}
 const match=url.pathname.match(/^\/api\/(tasks|timers|events)(?:\/([a-f0-9-]+))?$/);if(match){const kind=match[1],id=match[2];if(id&&!UUID.test(id))throw error('見つかりません。',404);if(request.method==='POST'&&!id){const body=await bodyJSON(request),value=cleanRecord(kind,body),recordId=body.id||crypto.randomUUID();if(!UUID.test(recordId))throw error('入力を確認してください。');const count=await env.DB.prepare('SELECT COUNT(*) AS count FROM home_records WHERE user_id=? AND kind=?').bind(user,kind).first();if(count.count>={tasks:100,timers:20,events:300}[kind])throw error('保存できる件数の上限です。不要な項目を削除してください。',409);const at=new Date().toISOString();await env.DB.prepare('INSERT OR IGNORE INTO home_records(user_id,kind,id,value,revision,updated_at) VALUES(?,?,?,?,1,?)').bind(user,kind,recordId,JSON.stringify(value),at).run();const row=await env.DB.prepare('SELECT id,value,revision,updated_at FROM home_records WHERE user_id=? AND kind=? AND id=?').bind(user,kind,recordId).first();return reply({record:recordRow(row)},201)}if(id&&['PUT','DELETE'].includes(request.method)){const body=await bodyJSON(request);number(body.revision,1,1e9);const existing=await env.DB.prepare('SELECT id,value,revision,updated_at FROM home_records WHERE user_id=? AND kind=? AND id=?').bind(user,kind,id).first();if(!existing)throw error('見つかりません。',404);if(existing.revision!==body.revision)return reply({error:'別の端末で更新されました。',record:recordRow(existing)},409);if(request.method==='DELETE'){const result=await env.DB.prepare('DELETE FROM home_records WHERE user_id=? AND kind=? AND id=? AND revision=?').bind(user,kind,id,body.revision).run();if(!result.meta.changes)throw error('別の端末で更新されました。',409);return reply({deleted:true})}const value=cleanRecord(kind,body),at=new Date().toISOString();const row=await env.DB.prepare('UPDATE home_records SET value=?,revision=revision+1,updated_at=? WHERE user_id=? AND kind=? AND id=? AND revision=? RETURNING id,value,revision,updated_at').bind(JSON.stringify(value),at,user,kind,id,body.revision).first();if(!row)throw error('別の端末で更新されました。',409);return reply({record:recordRow(row)})}throw error('対応していない操作です。',405)}
 if(url.pathname==='/api/calendar/sources'&&request.method==='POST'){const body=await bodyJSON(request),name=text(body.name,80,true),feedURL=googleCalendarURL(body.url),current=await sources(env.DB,user);if(current.length>=5)throw error('カレンダーは5つまで登録できます。',409);const source={id:crypto.randomUUID(),name,url:feedURL};const feed=await calendarFeed(source,env,user,true);const now=new Date().toISOString();await env.DB.prepare('INSERT INTO calendar_sources(user_id,id,name,url,updated_at) VALUES(?,?,?,?,?)').bind(user,source.id,name,feedURL,now).run();return reply({source:{id:source.id,name,provider:'google-ical',updatedAt:feed.updatedAt}},201)}
 const sourceId=url.pathname.match(/^\/api\/calendar\/sources\/([a-f0-9-]+)$/)?.[1];if(sourceId&&request.method==='DELETE'){if(!UUID.test(sourceId))throw error('見つかりません。',404);await env.DB.prepare('DELETE FROM calendar_sources WHERE user_id=? AND id=?').bind(user,sourceId).run();await env.BUCKET.delete('calendar-cache/'+encodeURIComponent(user)+'/'+sourceId+'.ics');return reply({deleted:true})}
 if(url.pathname==='/api/calendar'&&request.method==='GET'){const from=validISO(url.searchParams.get('from')),to=validISO(url.searchParams.get('to'));if(to<=from||Date.parse(to)-Date.parse(from)>62*86400000)throw error('表示期間を確認してください。');const result=await env.DB.prepare('SELECT id,name,url FROM calendar_sources WHERE user_id=? LIMIT 5').bind(user).all(),force=url.searchParams.get('refresh')==='1';const outcomes=await Promise.all(result.results.map(async source=>{try{const feed=await calendarFeed(source,env,user,force),parsed=parseCalendarICS(feed.raw,from,to,source);return{id:source.id,name:source.name,available:true,events:parsed.events,warnings:parsed.warnings,updatedAt:feed.updatedAt,stale:feed.stale,error:feed.error}}catch(e){return{id:source.id,name:source.name,available:false,error:e.message||'カレンダーを読み込めませんでした。',events:[]}}}));const google=await googleSources(env,user,from,to,force);return reply({sources:[...outcomes,...google],fetchedAt:new Date().toISOString()})}
 throw error('見つかりません。',404);
 }catch(e){return reply({error:e.status?e.message:'保存・読み込みに失敗しました。もう一度お試しください。'},e.status||503)}}
