'use strict';
const GoogleCalendar=(()=>{
 let data=null,busy=false,error='',code='',draft=null,retryAt=0,lastSuccess=null,loadedAt=0,sequence=0;
 async function request(path,options={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);try{const response=await fetch(path,{cache:'no-store',...options,signal:controller.signal});let result;try{result=await response.json()}catch{throw Error('Google連携の応答を読み込めませんでした。')}if(!response.ok)throw Object.assign(new Error(result.error||'Googleに接続できませんでした。'),{code:result.code,retryAfterMs:result.retryAfterMs,status:response.status});return result}catch(e){if(e.name==='AbortError')throw Error('接続に時間がかかっています。もう一度お試しください。');throw e}finally{clearTimeout(timer)}}
 const write=(path,method,value)=>request(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});
 function failure(e){error=e.message;code=e.code||'network_error';retryAt=Date.now()+(e.retryAfterMs||0)}
 async function load(force=false){if(busy||(!force&&Date.now()-loadedAt<300000))return;const seq=++sequence;busy=true;error='';render();try{data=await request('/api/google/status');if(data.connected&&data.configured)data=await request('/api/google/calendars');if(seq!==sequence)return;draft=new Set(data.selected||[]);lastSuccess=new Date().toISOString();loadedAt=Date.now();code=''}catch(e){failure(e)}finally{if(seq===sequence){busy=false;render()}}}
 function connectionHTML(){if(!data)return'<p class="help" role="status">'+(busy?'Googleへの接続を確認中…':esc(error||'接続を確認できませんでした。'))+'</p><button class="secondary" type="button" id="google-retry">再試行</button>';const blocked=Date.now()<retryAt;return`<div class="google-heading"><h3>Googleアカウント</h3>${data.connected?`<p class="help">${esc(data.email)}</p>`:''}</div>${!data.configured?'<p class="help">Google連携の初期設定が必要です。iCal連携は引き続き利用できます。</p>':''}${error?`<p class="stats-message" role="status">${esc(error)}${lastSuccess?' 前回の一覧を表示しています。':''}</p>`:''}${busy?'<p class="help" role="status">Googleカレンダーを更新中…</p>':''}<div class="row">${data.configured?`<form action="/api/google/connect" method="post" target="_top"><button class="${data.connected?'secondary':'primary'}" type="submit" ${busy?'disabled':''}>${data.connected?'再接続':'Googleに接続'}</button></form>`:''}${data.connected?`<button class="secondary" type="button" id="google-list-refresh" ${busy||blocked?'disabled':''}>一覧を更新</button><button class="text-button" type="button" id="google-disconnect" ${busy?'disabled':''}>接続を解除</button>`:''}${error||!data.connected?`<button class="secondary" type="button" id="google-retry" ${busy||blocked?'disabled':''}>再試行</button>`:''}</div>${data.connected?`<form id="google-calendar-selection"><fieldset ${busy?'disabled':''}><legend>表示するカレンダー</legend><div class="google-calendar-list">${data.calendars.map((c,index)=>`<div class="settings-switch-row"><label class="settings-label" id="google-calendar-label-${index}">${esc(c.name)}<span class="google-timezone">${esc(c.timeZone)}</span></label><button type="button" role="switch" aria-checked="${draft?.has(c.id)||false}" aria-labelledby="google-calendar-label-${index}" class="settings-switch" data-google-index="${index}"><span class="switch-track"><span class="switch-knob"></span></span></button></div>`).join('')}</div>${!data.calendars.length?'<p class="help">一覧を更新すると、選べるカレンダーを取得します。</p>':''}<div class="row"><button class="primary" type="submit" ${!data.configured||blocked?'disabled':''}>選択を保存</button><button class="secondary" type="button" id="google-events-refresh" ${!data.configured||blocked?'disabled':''}>予定を更新</button></div></fieldset></form><p class="help">読み取り専用 · 時刻はこの端末のタイムゾーン（${esc(Intl.DateTimeFormat().resolvedOptions().timeZone)}）で表示します。${lastSuccess?' 一覧更新：'+esc(new Date(lastSuccess).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})):''}</p>`:''}`}
 function render(){const host=$('#google-connection');if(!host)return;host.innerHTML=connectionHTML();if($('#google-retry'))$('#google-retry').onclick=()=>load(true);if($('#google-list-refresh'))$('#google-list-refresh').onclick=()=>load(true);$$('[data-google-index]').forEach(button=>button.onclick=()=>{const id=data.calendars[Number(button.dataset.googleIndex)].id;draft??=new Set(data.selected||[]);if(draft.has(id))draft.delete(id);else{if(draft.size>=10){toast('カレンダーは10個まで選べます。');return}draft.add(id)}button.setAttribute('aria-checked',String(draft.has(id)))});if($('#google-calendar-selection'))$('#google-calendar-selection').onsubmit=async event=>{event.preventDefault();if(busy)return;busy=true;error='';render();try{data=await write('/api/google/selection','PUT',{selected:[...draft],revision:data.revision,connectionId:data.connectionId});draft=new Set(data.selected);await Home.loadCalendar(true);toast('カレンダーの選択を保存しました。')}catch(e){failure(e);if(e.status===409)loadedAt=0}finally{busy=false;render()}};if($('#google-events-refresh'))$('#google-events-refresh').onclick=async()=>{if(busy)return;busy=true;render();await Home.loadCalendar(true);busy=false;render()};if($('#google-disconnect'))$('#google-disconnect').onclick=async()=>{if(busy)return;busy=true;render();try{const result=await write('/api/google/disconnect','POST',{revision:data.revision,connectionId:data.connectionId});data={...data,connected:false,calendars:[],selected:[],revision:0};draft=new Set();error='';lastSuccess=null;await Home.loadCalendar(true);toast(result.message||'Googleへの接続を解除しました。')}catch(e){failure(e);loadedAt=0}finally{busy=false;render()}};if(retryAt>Date.now())setTimeout(()=>{if(Date.now()>=retryAt)render()},Math.min(3600000,retryAt-Date.now()+100))}
 function calendarErrors(sources){const failed=sources.filter(s=>s.provider==='google-api'&&s.code);if(!failed.length)return;const reconnect=failed.find(s=>s.code==='reauthentication_required');if(reconnect){error=reconnect.error;code=reconnect.code;render();$('#google-connection')?.closest('details')?.setAttribute('open','')}const delay=Math.max(0,...failed.map(s=>s.retryAfterMs||0));if(delay){retryAt=Date.now()+delay;render()}}
 function init(){const url=new URL(location.href),result=url.searchParams.get('google');if(result){url.searchParams.delete('google');history.replaceState(null,'',url.pathname+url.search+url.hash);const messages={connected:'Googleアカウントを接続しました。',denied:'Googleへの接続をキャンセルしました。',invalid_state:'接続の有効時間が切れたか、別の画面から戻りました。もう一度接続してください。',not_configured:'Google連携の初期設定が必要です。',permission:'カレンダーの読み取り権限を許可して、もう一度接続してください。',reconnect:'継続して読み込む権限を取得できませんでした。もう一度接続してください。',failed:'Googleへの接続を完了できませんでした。もう一度お試しください。'};wake();openPanel('calendar');$('#google-connection')?.closest('details')?.setAttribute('open','');toast(messages[result]||messages.failed)}window.addEventListener('online',()=>{loadedAt=0;if(currentPanel==='calendar')load(true)});load()}
 return{init,load,render,calendarErrors};
})();
