'use strict';
const AuraHub=(()=>{
 const titles={news:'ニュース',today:'今日のまとめ',transit:'交通',sports:'スポーツ',entertainment:'映画・アニメ',worldclock:'世界時計'};
 const topics={top:'主要',society:'社会',science:'科学・技術',business:'経済',world:'国際',sports:'スポーツ',culture:'文化・音楽'};
 const defaults={displayName:'',newsTopic:'top',newsSource:'nhk',musicService:'spotify',widgets:[],timezones:['Asia/Tokyo','Europe/London','America/New_York'],notifications:{agenda:false,weather:false,news:false},transit:[],sportsTeam:{id:'133604',name:'Arsenal'},watchlist:[],savedNews:[]};
 let data={...defaults},account=null,accountError='',accountBusy=false,accountView='profile',nameDraft=null,appState={},panelErrors={},pending=new Set(),home=null,worldTimer=null,diagnostics=null;
 const safeURL=v=>{try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password?u.href:null}catch{return null}};
 const link=(url,label)=>safeURL(url)?`<a class="hub-link" href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`:'';
 const localTime=value=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('ja-JP',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}):'日程未定';
 const button=(id,label,primary=false)=>`<button type="button" id="${id}" class="${primary?'primary':'secondary'}">${label}</button>`;
 const status=(id,result)=>`<p class="help" role="status">${pending.has(id)?'更新中…':panelErrors[id]||result?.message||''}${result?.stale?' 前回の情報を表示しています。':''}${result?.updatedAt?' · '+localTime(result.updatedAt)+' 更新':''}</p>`;
 function snapshot(){return structuredClone(data)}
 function apply(value){data={...defaults,...value,notifications:{...defaults.notifications,...value.notifications}};set('hub',data);updateAvatar();renderWidgets();if(titles[currentPanel]&&!pending.has(currentPanel))render(currentPanel)}
 function change(patch){data={...data,...patch};set('hub',data);updateAvatar();renderWidgets()}
 function init(){data={...defaults,...get('hub',{}),notifications:{...defaults.notifications,...get('hub',{}).notifications}};worldTimer=setInterval(()=>{if(currentPanel==='worldclock')renderClocks();renderWidgetClocks();notifyAgenda()},30000);$('#home-widgets')?.addEventListener('click',e=>{const target=e.target.closest('[data-widget-app]');if(target)openPanel(target.dataset.widgetApp,target)});renderWidgets()}
 function update(state){home=state;updateAvatar();renderWidgets()}
 function updateAvatar(){const el=$('#account-open'),profile=account?.profile||home?.account||{};if(!el)return;const name=data.displayName||profile.name||profile.email||'アカウント';el.title=name;el.setAttribute('aria-label',name+'のアカウント設定を開く');const avatar=safeURL(profile.avatar);const initial=`<span class="account-initial" aria-hidden="true">${esc(name.charAt(0).toUpperCase())}</span>`;el.innerHTML=avatar?`<img src="${esc(avatar)}" referrerpolicy="no-referrer" alt="">`:initial;const photo=el.querySelector('img');if(photo)photo.onerror=()=>{el.innerHTML=initial}}
 async function loadAccount(force=false){if(accountBusy||account&&!force)return;accountBusy=true;accountError='';renderAccount();try{account=await Home.api('/api/account')}catch(e){accountError=e.message}finally{accountBusy=false;updateAvatar();if(currentPanel==='settings'&&settingsTab==='account')renderAccount()}}
 const field=(id,label,value='',type='text')=>`<label class="field"><span class="field-label">${label}</span><input id="${id}" type="${type}" value="${esc(value)}" maxlength="160"></label>`;
 function renderAccount(){if(currentPanel!=='settings'||settingsTab!=='account')return;const profile=account?.profile||home?.account||{};
  const views={profile:'プロフィール',services:'連携・通知',devices:'端末',data:'バックアップ',display:'端末設定',widgets:'ウィジェット'};
  $('#settings-view').innerHTML=`<div class="account-summary"><div class="profile-avatar">${safeURL(profile.avatar)?`<img alt="" src="${esc(profile.avatar)}" referrerpolicy="no-referrer">`:`<span>${esc((data.displayName||profile.name||profile.email||'A').charAt(0).toUpperCase())}</span>`}</div><div><h3>${esc(data.displayName||profile.name||'アカウント設定')}</h3><p class="help">${esc(profile.email||'読み込み中…')}</p><span class="hub-badge">${profile.provider==='google'?'Googleでログイン中':'メールでログイン中'}</span></div></div><nav class="hub-tabs" aria-label="アカウント設定の項目">${Object.entries(views).map(([id,label])=>`<button type="button" data-account-view="${id}" aria-pressed="${id===accountView}" class="stats-segment ${id===accountView?'selected':''}">${label}</button>`).join('')}</nav><p class="help" role="status">${accountBusy?'アカウントを確認中…':esc(accountError)}</p><div id="account-detail"></div>`;
  const host=$('#account-detail');
  if(accountView==='profile')host.innerHTML=`<div class="settings-card">${field('profile-name','表示名',nameDraft??data.displayName??profile.name)}${button('profile-save','表示名を保存',true)}<p class="help">Googleのプロフィール画像はGoogleでログインした後に表示されます。</p></div><div class="settings-card"><h4>Googleアカウント</h4>${profile.googleLoginAvailable?'<form method="post" action="/auth/google/switch"><button class="primary">Googleアカウントを選び直す</button></form><p class="help">自分のGoogleアカウントで利用できます。カレンダー用アカウントは連携画面で選べます。</p>':'<p class="help">Googleログインの初期設定が必要です。現在のメールログインは利用できます。</p>'}<form method="post" action="/auth/logout"><button class="secondary">この端末からログアウト</button></form></div><div class="settings-card"><h4>アカウントを削除</h4><p class="help">設定・予定・ToDo・画像・バックアップとログイン情報を削除します。元に戻せません。必要なデータは先に書き出してください。</p>${field('delete-confirm-email','確認のためメールアドレスを入力','')}<button type="button" class="secondary" id="account-delete" disabled>アカウントと保存データを削除</button></div>`;
  if(accountView==='services')host.innerHTML=`<div class="settings-card"><h4>Googleカレンダー</h4><p class="help">読み取り専用で連携します。連携先の変更・カレンダーの選択・再接続を管理できます。</p>${button('hub-google','Google連携を設定',true)}</div><div class="settings-card"><h4>音楽</h4><p class="help">stats.fmの公開プロフィールから、再生履歴やランキングを読み込みます。</p>${button('hub-music','音楽プロフィールを設定')}<label class="field"><span class="field-label">曲を開くサービス</span><select id="music-service">${[['spotify','Spotify'],['apple','Apple Music'],['youtube','YouTube Music']].map(([v,t])=>`<option value="${v}" ${v===data.musicService?'selected':''}>${t}</option>`).join('')}</select></label></div><div class="settings-card"><h4>通知</h4>${Object.entries({agenda:'予定の開始',weather:'天気の更新',news:'ニュースの更新'}).map(([id,label])=>`<label class="hub-check"><input type="checkbox" data-notification="${id}" ${data.notifications[id]?'checked':''}>${label}</label>`).join('')}<p class="help">この端末でアプリを開いている間に通知します。端末ごとに通知の許可が必要です。</p>${button('hub-notification-enable','この端末で通知を許可')}<p class="help" id="notification-permission">${notificationPermission()}</p></div><div class="settings-card"><h4>接続の診断</h4>${button('hub-diagnose','接続を確認')}<div id="diagnostic-results">${diagnosticHTML()}</div></div>`;
  if(accountView==='devices')host.innerHTML=`<div class="settings-card"><h4>ログイン中の端末</h4><div class="hub-list">${(account?.devices||[]).map(d=>`<div class="hub-list-item"><div><strong>${esc(d.name)}</strong><p class="help">${d.current?'この端末 · ':''}${d.revoked?'ログアウト済み · ':''}${localTime(d.lastSeen)}</p></div>${!d.current&&!d.revoked?`<button class="secondary" type="button" data-revoke-device="${d.id}">ログアウト</button>`:''}</div>`).join('')||'<p class="help">端末を読み込みます。</p>'}</div>${button('devices-refresh','一覧を更新')}${button('devices-revoke-others','他の端末をすべてログアウト')}</div>`;
  if(accountView==='data')host.innerHTML=`<div class="settings-card"><h4>設定のバックアップ</h4><p class="help">現在の同期設定をサーバーへ保存します。復元前の設定もバックアップしておくと戻せます。</p>${button('backup-create','今の設定をバックアップ',true)}<div class="hub-list">${(account?.backups||[]).map(b=>`<div class="hub-list-item"><span>${localTime(b.createdAt)}</span><button type="button" class="secondary" data-restore-backup="${b.id}">復元</button></div>`).join('')||'<p class="help">バックアップはまだありません。</p>'}</div></div><div class="settings-card"><h4>データを書き出す</h4><p class="help">設定・ToDo・予定・タイマーをJSONで保存します。Googleの接続トークンは含めません。</p><a class="hub-link" href="/api/account/export" download>JSONをダウンロード ↓</a><label class="field"><span class="field-label">書き出したJSONから設定を復元</span><input type="file" id="settings-import" accept="application/json,.json"></label></div>`;
  if(accountView==='display')host.innerHTML=`<div class="settings-card"><h4>この端末の表示</h4><label class="hub-check"><input type="checkbox" id="device-display-only" ${Home.getSync()?'':'checked'}>表示・情報アプリの設定をこの端末で管理する</label><p class="help">端末専用を有効にすると、時計・背景・アプリ順・情報アプリの設定の同期を止めます。ToDo・予定・タイマーは引き続きサーバーから読み込みます。</p>${field('device-label','この端末の呼び名',get('device-label',''))}${button('device-label-save','端末名を保存')}<p class="help">${get('device-label','')?'端末名：'+esc(get('device-label','')):''}</p></div><div class="settings-card"><h4>設定の同期</h4><p id="sync-status" class="help" role="status"></p>${button('sync-now','今すぐ同期')}</div>`;
  if(accountView==='widgets')host.innerHTML=`<div class="settings-card"><h4>ホームに表示する情報</h4>${Object.entries({weather:'天気',agenda:'今日の予定',news:'ニュース',worldclock:'世界時計'}).map(([id,t])=>`<label class="hub-check"><input type="checkbox" data-widget-setting="${id}" ${data.widgets.includes(id)?'checked':''}>${t}</label>`).join('')}<p class="help">時計画面に小さな情報カードを表示します。</p></div>`;
  $$('[data-account-view]').forEach(b=>b.onclick=()=>{accountView=b.dataset.accountView;renderAccount();if(!account)loadAccount()});
  if($('#delete-confirm-email'))$('#delete-confirm-email').oninput=()=>$('#account-delete').disabled=$('#delete-confirm-email').value.trim()!==profile.email;
  if($('#account-delete'))$('#account-delete').onclick=async()=>{if(!confirm('このアカウントと保存データを削除します。元に戻せません。削除しますか？'))return;const b=$('#account-delete');b.disabled=true;try{await Home.write('/api/account/delete','POST',{confirm:$('#delete-confirm-email').value.trim()});localStorage.clear();location.replace('/signin?account_deleted=1')}catch(e){toast(e.message);b.disabled=false}};
  if($('#profile-name'))$('#profile-name').oninput=e=>nameDraft=e.target.value;
  if($('#profile-save'))$('#profile-save').onclick=async()=>{change({displayName:$('#profile-name').value.trim().slice(0,80)});const saved=await Home.syncSettings();nameDraft=null;renderAccount();toast(saved?'表示名を保存しました。':Home.getSync()?'この端末に保存しました。接続後に同期します。':'表示名をこの端末に保存しました。')};
  if($('#hub-google'))$('#hub-google').onclick=()=>{openPanel('calendar');$('#google-connection')?.closest('details')?.setAttribute('open','')};
  if($('#hub-music'))$('#hub-music').onclick=()=>openPanel('stats');
  if($('#music-service'))$('#music-service').onchange=e=>change({musicService:e.target.value});
  $$('[data-notification]').forEach(b=>b.onchange=()=>change({notifications:{...data.notifications,[b.dataset.notification]:b.checked}}));
  if($('#hub-notification-enable'))$('#hub-notification-enable').onclick=async()=>{if(!('Notification'in window)){toast('このブラウザでは通知を利用できません。');return}await Notification.requestPermission();$('#notification-permission').textContent=notificationPermission()};
  if($('#hub-diagnose'))$('#hub-diagnose').onclick=async()=>{try{diagnostics=await Home.api('/api/account/diagnostics');$('#diagnostic-results').innerHTML=diagnosticHTML()}catch(e){toast(e.message)}};
  if($('#devices-refresh'))$('#devices-refresh').onclick=()=>loadAccount(true);
  $$('[data-revoke-device]').forEach(b=>b.onclick=()=>revokeDevice(b.dataset.revokeDevice));
  if($('#devices-revoke-others'))$('#devices-revoke-others').onclick=async()=>{if(!confirm('この端末を残して、他の端末をすべてログアウトしますか？'))return;try{await accountAction('/api/account/devices/revoke-others',{});await loadAccount(true)}catch{}};
  if($('#backup-create'))$('#backup-create').onclick=async()=>{try{if(Home.getSync()&&!await Home.syncSettings()){toast('設定の同期が完了してからバックアップしてください。');return}await accountAction('/api/account/backups',{});await loadAccount(true)}catch{}};
  $$('[data-restore-backup]').forEach(b=>b.onclick=async()=>{if(!confirm('このバックアップの設定を復元しますか？現在の設定を置き換えます。'))return;await restore({backupId:b.dataset.restoreBackup})});
  if($('#settings-import'))$('#settings-import').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>4194304)throw Error('ファイルは4MB以下にしてください。');const imported=JSON.parse(await file.text());if(imported.format!=='aura-home'||imported.version!==1)throw Error('Aura Homeの書き出しファイルを選んでください。');if(confirm('このファイルの設定を復元しますか？'))await restore({settings:imported.settings})}catch(e){toast(e.message)}};
  if($('#device-display-only'))$('#device-display-only').onchange=async e=>{await Home.setSync(!e.target.checked);renderAccount()};
  if($('#device-label-save'))$('#device-label-save').onclick=()=>{set('device-label',$('#device-label').value.slice(0,80));toast('端末名を保存しました。')};
  if($('#sync-now'))$('#sync-now').onclick=async()=>{await Home.reload(true);await Home.syncSettings();renderAccount()};
  $$('[data-widget-setting]').forEach(b=>b.onchange=()=>change({widgets:$$('[data-widget-setting]').filter(x=>x.checked).map(x=>x.dataset.widgetSetting)}));
  Home.updateSyncUI();if(!account&&!accountBusy)loadAccount();
 }
 function notificationPermission(){return !('Notification'in window)?'この環境では通知を利用できません。':({granted:'この端末の通知は許可されています。',denied:'通知はブロックされています。ブラウザの設定から変更できます。',default:'この端末の通知はまだ許可されていません。'})[Notification.permission]}
 function diagnosticHTML(){return diagnostics?`<dl class="hub-diagnostics">${Object.entries({auth:'ログイン',database:'保存先',storage:'画像保存',googleLogin:'Googleログインの設定',googleCalendar:'Googleカレンダーの設定'}).map(([key,t])=>`<div><dt>${t}</dt><dd>${diagnostics[key]?(key.startsWith('google')?'設定済み':'接続済み'):'初期設定が必要'}</dd></div>`).join('')}</dl><p class="help">${localTime(diagnostics.checkedAt)} 確認</p>`:''}
 async function accountAction(path,body){try{const r=await Home.write(path,'POST',body);toast('完了しました。');return r}catch(e){toast(e.message);throw e}}
 async function revokeDevice(id){if(!confirm('この端末をログアウトしますか？再利用するにはサインインが必要です。'))return;try{await accountAction('/api/account/devices/revoke',{id});await loadAccount(true)}catch{}}
 async function restore(body){try{if(!Home.getSync()){toast('設定の同期を有効にしてから復元してください。');return}if(!await Home.syncSettings()){toast('設定の同期が完了してから復元してください。');return}await accountAction('/api/account/restore',{...body,revision:Home.getState().revision});await Home.reload(true);nameDraft=null;renderAccount()}catch{}}
 function render(type){if(!titles[type])return false;const host=$('#panel-content');if(type==='worldclock'){renderWorld(host);return true}if(type==='transit'){renderTransit(host);return true}if(type==='today'){renderToday(host);return true}if(type==='news'){renderNews(host);return true}if(type==='sports'){renderSports(host);return true}if(type==='entertainment'){renderEntertainment(host);return true}return false}
 function opened(type){if(!titles[type])return;render(type);if(type==='news')loadInfo(type);if(type==='sports')loadInfo(type);if(type==='entertainment')loadInfo(type,'anime');if(type==='transit'&&data.transit.length)loadInfo(type,data.transit[0].operator);if(type==='today'){Home.loadCalendar(false).then(()=>{if(currentPanel==='today')render(type)});loadInfo('news');refreshWeather()}}
 async function loadInfo(kind,arg){if(pending.has(kind))return;pending.add(kind);panelErrors[kind]='';if(currentPanel===kind||currentPanel==='today')render(currentPanel);let query='';if(kind==='news')query='?topic='+data.newsTopic+'&source='+data.newsSource;if(kind==='sports')query='?team='+encodeURIComponent(data.sportsTeam.id);if(kind==='entertainment')query='?mode='+(arg||'anime');if(kind==='transit')query='?operator='+(arg||'TokyoMetro');try{appState[kind]=await Home.api('/api/info/'+kind+query);panelErrors[kind]=appState[kind].error||'';if(kind==='news')notify('news','ニュースが更新されました',appState.news.items?.[0]?.title,appState.news.items?.[0]?.url);renderWidgets()}catch(e){panelErrors[kind]=e.message}finally{pending.delete(kind);if(currentPanel===kind||currentPanel==='today')render(currentPanel)}}
 function newsCards(items,saved=false){return items.length?`<div class="hub-list">${items.map((n,i)=>`<article class="hub-news"><p class="hub-kicker">${esc(n.source||'ニュース')} ${n.date?localTime(n.date):''}</p>${link(n.url,n.title)}<button type="button" class="text-button" data-save-news="${i}">${saved?'保存から外す':data.savedNews.some(x=>x.url===n.url)?'保存済み':'あとで読む'}</button></article>`).join('')}</div>`:'<p class="help">表示する記事はありません。</p>'}
 function renderNews(host){const result=appState.news;host.innerHTML=`<div class="hub-controls"><label class="field"><span class="field-label">ジャンル</span><select id="news-topic">${Object.entries(topics).map(([v,t])=>`<option value="${v}" ${v===data.newsTopic?'selected':''}>${t}</option>`).join('')}</select></label><label class="field"><span class="field-label">情報源</span><select id="news-source"><option value="nhk" ${data.newsSource==='nhk'?'selected':''}>NHK</option><option value="google" ${data.newsSource==='google'?'selected':''}>Googleニュース</option></select></label>${button('news-refresh','更新')}</div>${status('news',result)}${result?newsCards(result.items):'<p class="help">ニュースを読み込みます。</p>'}<details><summary>あとで読む (${data.savedNews.length})</summary><div class="hub-list">${data.savedNews.map((n,i)=>`<article class="hub-news">${link(n.url,n.title)}<button class="text-button" type="button" data-remove-news="${i}">保存から外す</button></article>`).join('')}</div></details><p class="attribution">見出し提供：${esc(result?.source||'選択した情報源')}。記事は情報元のサイトで開きます。</p>`;$('#news-topic').onchange=e=>{change({newsTopic:e.target.value});loadInfo('news')};$('#news-source').onchange=e=>{change({newsSource:e.target.value});loadInfo('news')};$('#news-refresh').onclick=()=>loadInfo('news');$$('[data-save-news]').forEach(b=>b.onclick=()=>{const n=result.items[Number(b.dataset.saveNews)];if(data.savedNews.some(x=>x.url===n.url))return;if(data.savedNews.length>=40){toast('保存は40件までです。');return}change({savedNews:[...data.savedNews,{title:n.title,url:n.url,source:n.source}]});render('news')});$$('[data-remove-news]').forEach(b=>b.onclick=()=>{change({savedNews:data.savedNews.filter((_,i)=>i!==Number(b.dataset.removeNews))});render('news')})}
 function weatherCard(){const valid=weather&&weather.place===locationData?.name;return `<div class="hub-info-card"><h3>天気</h3>${valid?`<strong class="hub-temperature">${Math.round(weather.current.temperature_2m)}°</strong><p>${esc(weather.place)} · ${weatherInfo(weather.current.weather_code)[0]}</p>`:'<p class="help">地域を設定すると天気を表示します。</p>'}${button('today-weather','天気を開く')}</div>`}
 function agendaHTML(){const today=Home.dayString(new Date()),events=Home.eventsForDay(today);return events.length?events.slice(0,5).map(e=>`<div class="hub-list-item"><span>${e.allDay?'終日':new Date(e.start).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}</span><strong>${esc(e.title)}</strong></div>`).join(''):'<p class="help">今日の予定はありません。</p>'}
 function renderToday(host){host.innerHTML=`<p class="hub-kicker">${new Date().toLocaleDateString('ja-JP',{month:'long',day:'numeric',weekday:'long'})}</p><div class="hub-grid">${weatherCard()}<div class="hub-info-card"><h3>今日の予定</h3>${agendaHTML()}${button('today-calendar','カレンダーを開く')}</div><div class="hub-info-card"><h3>ToDo</h3>${(home?.tasks||[]).filter(t=>!t.done).slice(0,4).map(t=>`<p>${esc(t.title)}</p>`).join('')||'<p class="help">未完了のToDoはありません。</p>'}${button('today-tasks','ToDoを開く')}</div><div class="hub-info-card"><h3>ニュース</h3>${status('news',appState.news)}${(appState.news?.items||[]).slice(0,3).map(n=>`<p>${link(n.url,n.title)}</p>`).join('')}${button('today-news','ニュースを開く')}</div><div class="hub-info-card"><h3>音楽</h3><p class="help">最近聴いた曲とランキング。</p>${button('today-music','音楽を開く')}</div><div class="hub-info-card"><h3>次の出発</h3>${departureHTML()}${button('today-transit','交通を開く')}</div></div>`;for(const[id,app]of [['weather','weather'],['calendar','calendar'],['tasks','tasks'],['news','news'],['music','stats'],['transit','transit']])$('#today-'+id).onclick=()=>openPanel(app)}
 const transitLinks={TokyoMetro:'https://www.tokyometro.jp/unkou/index.html','JR-East':'https://traininfo.jreast.co.jp/train_info/kanto.aspx',Toei:'https://www.kotsu.metro.tokyo.jp/subway/schedule/'};
 function nextDeparture(route){const now=new Date(),minute=now.getHours()*60+now.getMinutes();const time=route.times.find(t=>Number(t.slice(0,2))*60+Number(t.slice(3))>=minute);return time?{time,tomorrow:false}:route.times.length?{time:route.times[0],tomorrow:true}:null}
 function departureHTML(){const candidates=data.transit.map(r=>({r,next:nextDeparture(r)})).filter(x=>x.next);if(!candidates.length)return'<p class="help">路線と普段の出発時刻を登録できます。</p>';return candidates.map(({r,next})=>`<p><strong>${next.tomorrow?'明日 ':''}${next.time}</strong> ${esc(r.name)}</p>`).join('')}
 function renderTransit(host){const result=appState.transit;host.innerHTML=`<div class="hub-info-card"><h3>次の出発</h3>${departureHTML()}<p class="help">出発時刻は登録した通常の時刻です。遅延は反映しません。</p></div><div class="hub-list">${data.transit.map((r,i)=>`<article class="hub-info-card"><h3>${esc(r.name)}</h3><p>${r.times.join(' · ')||'出発時刻未登録'}</p>${link(transitLinks[r.operator],'公式の運行情報')}<div class="row"><button class="secondary" type="button" data-transit-live="${r.operator}">運行情報を更新</button><button class="text-button" type="button" data-transit-remove="${i}">登録を外す</button></div></article>`).join('')}</div>${status('transit',result)}${(result?.items||[]).map(r=>`<div class="hub-info-card"><strong>${esc(r.title.replace(/^odpt\.Railway:/,''))}</strong><p>${esc(r.text)}</p><small>${localTime(r.date)}</small></div>`).join('')}<details open><summary>路線と出発時刻を登録</summary><form id="transit-form">${field('transit-name','路線・区間名')}<label class="field"><span class="field-label">交通事業者</span><select id="transit-operator"><option value="TokyoMetro">東京メトロ</option><option value="JR-East">JR東日本</option><option value="Toei">都営地下鉄</option></select></label>${field('transit-times','出発時刻（例：08:15, 08:30, 09:00）')}<button class="primary">登録</button></form></details>`;$$('[data-transit-live]').forEach(b=>b.onclick=()=>loadInfo('transit',b.dataset.transitLive));$$('[data-transit-remove]').forEach(b=>b.onclick=()=>{change({transit:data.transit.filter((_,i)=>i!==Number(b.dataset.transitRemove))});render('transit')});$('#transit-form').onsubmit=e=>{e.preventDefault();if(data.transit.length>=8){toast('路線は8件までです。');return}const name=$('#transit-name').value.trim(),times=$('#transit-times').value.split(/[、,\s]+/).filter(Boolean);if(!name||times.length>30||times.some(t=>!/^([01]\d|2[0-3]):[0-5]\d$/.test(t))){toast('路線名と24時間表記の出発時刻を確認してください。');return}change({transit:[...data.transit,{name,operator:$('#transit-operator').value,times:[...new Set(times)].sort()}]});render('transit');Home.syncSettings()}}
 function renderSports(host){const result=appState.sports;host.innerHTML=`<div class="hub-info-card"><h3>${esc(result?.team?.name||data.sportsTeam.name)}</h3><p class="help">${esc(result?.team?.sport||'')} ${esc(result?.team?.league||'')}</p>${button('sports-refresh','試合情報を更新')}${status('sports',result)}${result?.limited?'<p class="help">無料データでは表示件数や対象試合が限られます。ライブ速報ではありません。</p>':''}</div><div class="hub-list">${(result?.items||[]).map(e=>`<article class="hub-info-card"><p class="hub-kicker">${e.upcoming?'次の試合':'試合結果'} · ${localTime(e.date)}</p><h3>${esc(e.title)}</h3>${e.homeScore!==null&&e.homeScore!==undefined?`<strong class="hub-score">${esc(e.homeScore)} : ${esc(e.awayScore??'—')}</strong>`:''}</article>`).join('')||'<p class="help">取得できた試合はありません。</p>'}</div><details><summary>好きなチームを設定</summary><form id="sports-form">${field('sports-name','表示するチーム名',data.sportsTeam.name)}${field('sports-id','TheSportsDB チームID',data.sportsTeam.id)}<p class="help">TheSportsDBのチームページにある数字のIDを指定します。</p>${link('https://www.thesportsdb.com/','チームを探す')}<button class="primary">保存</button></form></details><p class="attribution">Sports data by TheSportsDB</p>`;$('#sports-refresh').onclick=()=>loadInfo('sports');$('#sports-form').onsubmit=e=>{e.preventDefault();const id=$('#sports-id').value.trim(),name=$('#sports-name').value.trim();if(!/^\d{1,10}$/.test(id)||!name){toast('チーム名と数字のIDを入力してください。');return}change({sportsTeam:{id,name}});appState.sports=null;loadInfo('sports')}}
 function renderEntertainment(host){const result=appState.entertainment;host.innerHTML=`<div class="row">${button('anime-upcoming','今後のアニメ')}${button('movie-upcoming','公開予定の映画')}</div>${status('entertainment',result)}<div class="hub-list">${(result?.items||[]).map((r,i)=>`<article class="hub-info-card"><p class="hub-kicker">${esc(r.date||'日程未定')}</p><h3>${esc(r.title)}</h3>${link(r.url,'作品情報')}<button class="text-button" type="button" data-watch-add="${i}">${data.watchlist.some(x=>x.id===r.type+':'+r.id)?'保存済み':'気になる作品に保存'}</button></article>`).join('')}</div><h3>気になる作品</h3><div class="hub-list">${data.watchlist.map((r,i)=>`<article class="hub-info-card"><p class="hub-kicker">${esc(r.date||'日程未定')} · ${r.type==='movie'?'映画':r.type==='anime'?'アニメ':'TV'}</p><h3>${esc(r.title)}</h3>${link(r.url,'公式・作品ページ')}<button type="button" class="text-button" data-watch-remove="${i}">保存から外す</button></article>`).join('')||'<p class="help">気になる映画・アニメを保存できます。</p>'}</div><details><summary>作品を手動で追加</summary><form id="watch-form">${field('watch-title','作品名')}${field('watch-date','公開・配信予定日','','date')}<label class="field"><span class="field-label">種類</span><select id="watch-type"><option value="movie">映画</option><option value="anime">アニメ</option><option value="tv">TV</option></select></label>${field('watch-url','公式・作品ページ（任意）','','url')}<button class="primary">保存</button></form></details><p class="attribution">${result?.source==='TMDB'?'This product uses the TMDB API but is not endorsed or certified by TMDB.':result?.source?'Anime data by Jikan / MyAnimeList':''}</p>`;$('#anime-upcoming').onclick=()=>loadInfo('entertainment','anime');$('#movie-upcoming').onclick=()=>loadInfo('entertainment','movie');const add=r=>{if(data.watchlist.length>=40){toast('作品は40件までです。');return}if(data.watchlist.some(x=>x.id===r.id))return;change({watchlist:[...data.watchlist,r]});render('entertainment')};$$('[data-watch-add]').forEach(b=>b.onclick=()=>{const r=result.items[Number(b.dataset.watchAdd)];add({...r,id:r.type+':'+r.id,date:r.date||''})});$$('[data-watch-remove]').forEach(b=>b.onclick=()=>{change({watchlist:data.watchlist.filter((_,i)=>i!==Number(b.dataset.watchRemove))});render('entertainment')});$('#watch-form').onsubmit=e=>{e.preventDefault();const title=$('#watch-title').value.trim(),url=$('#watch-url').value.trim();if(!title||url&&!safeURL(url)){toast('作品名とHTTPSのURLを確認してください。');return}add({id:crypto.randomUUID(),title,date:$('#watch-date').value,type:$('#watch-type').value,url})}}
 const zoneNames={'Asia/Tokyo':'東京','Europe/London':'ロンドン','America/New_York':'ニューヨーク','America/Los_Angeles':'ロサンゼルス','Europe/Paris':'パリ','Asia/Singapore':'シンガポール','Australia/Sydney':'シドニー','Asia/Seoul':'ソウル','Asia/Taipei':'台北','Asia/Dubai':'ドバイ'};
 function clockHTML(zone){const now=new Date();return`<article class="hub-clock"><span>${esc(zoneNames[zone]||zone)}</span><strong>${new Intl.DateTimeFormat('ja-JP',{timeZone:zone,hour:'2-digit',minute:'2-digit',hour12:false}).format(now)}</strong><small>${new Intl.DateTimeFormat('ja-JP',{timeZone:zone,month:'numeric',day:'numeric',weekday:'short'}).format(now)}</small></article>`}
 function renderClocks(){if($('#world-clocks'))$('#world-clocks').innerHTML=data.timezones.map(clockHTML).join('')}
 function renderWorld(host){host.innerHTML=`<div class="hub-grid" id="world-clocks"></div><div class="settings-card"><h3>表示する都市</h3>${Object.entries(zoneNames).map(([zone,t])=>`<label class="hub-check"><input type="checkbox" data-zone="${zone}" ${data.timezones.includes(zone)?'checked':''}>${t}</label>`).join('')}<p class="help">6都市まで表示できます。夏時間は各都市のタイムゾーンに合わせます。</p></div>`;renderClocks();$$('[data-zone]').forEach(b=>b.onchange=()=>{const selected=$$('[data-zone]').filter(x=>x.checked).map(x=>x.dataset.zone);if(selected.length>6){b.checked=false;toast('都市は6つまでです。');return}change({timezones:selected});renderClocks()})}
 function renderWidgets(){const host=$('#home-widgets');if(!host)return;host.hidden=data.widgets.length===0;host.innerHTML=data.widgets.map(id=>{let value='設定すると表示します',app=id==='agenda'?'calendar':id;if(id==='weather'&&weather?.place===locationData?.name)value=`${Math.round(weather.current.temperature_2m)}° · ${weather.place}`;if(id==='agenda')value=Home?.eventsForDay(Home.dayString(new Date()))?.[0]?.title||'今日の予定はありません';if(id==='news')value=appState.news?.items?.[0]?.title||'ニュースを開いて更新';if(id==='worldclock')value=data.timezones.slice(0,2).map(z=>(zoneNames[z]||z)+' '+new Intl.DateTimeFormat('ja-JP',{timeZone:z,hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date())).join(' · ');return`<button class="home-widget" type="button" data-widget-app="${app}"><span>${({weather:'天気',agenda:'予定',news:'ニュース',worldclock:'世界時計'})[id]}</span><strong>${esc(value)}</strong></button>`}).join('')}
 function renderWidgetClocks(){if(data.widgets.includes('worldclock'))renderWidgets()}
 async function notify(kind,title,message,key){if(!data.notifications[kind]||!message||!('Notification'in window)||Notification.permission!=='granted')return;const seen=get('notice-seen',{}),id=kind+':'+key;if(seen[id])return;seen[id]=Date.now();set('notice-seen',Object.fromEntries(Object.entries(seen).sort((a,b)=>b[1]-a[1]).slice(0,80)));try{const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body:message,tag:kind,icon:'/icon-192.png'})}catch{}}
 function notifyAgenda(){if(!home)return;const events=Home.eventsForDay(Home.dayString(new Date()));for(const e of events){const delta=Date.parse(e.start)-Date.now();if(!e.allDay&&delta>=-60000&&delta<=300000)notify('agenda','まもなく予定が始まります',e.title,e.id+':'+e.start)}}
 function weatherUpdated(){renderWidgets();if(currentPanel==='today')render('today');if(weather?.current)notify('weather','天気が更新されました',weather.place+' '+weatherInfo(weather.current.weather_code)[0]+' '+Math.round(weather.current.temperature_2m)+'°',weather.place+':'+new Date().toDateString())}
 function musicLink(title,artist){const q=encodeURIComponent([title,artist].filter(Boolean).join(' '));return data.musicService==='apple'?'https://music.apple.com/jp/search?term='+q:data.musicService==='youtube'?'https://music.youtube.com/search?q='+q:'https://open.spotify.com/search/'+q}
 return{init,snapshot,apply,update,renderAccount,render,opened,titles,renderWidgets,weatherUpdated,musicLink,loadAccount};
})();
